### PR TITLE
Implement `pin.calibrate()` method.

### PR DESCRIPTION
**Pull request by dpgeorge**
Added only to pins that have touch capabilities.

Addresses issue #209.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Maybe it should be called `pin.touch_calibrate()` to make it clear what it does?

**Comment by microbit-carlos** [comment]
Thanks Damien!

> Maybe it should be called `pin.touch_calibrate()` to make it clear what it does?

Yeah, that's a good call, I agree that name is better.

**Comment by dpgeorge** [comment]
Updated to change the name to `touch_calibrate()`.

**Review by microbit-carlos — APPROVED** [review]
Tested and works great, thanks Damien!

**Pull request merged**
