### PR TITLE
Implement `display.rotate(degrees)` method.

### PR DESCRIPTION
**Pull request by dpgeorge**
This takes an angle in degrees and rounds it towards the nearest multiple of 90.  All integer values of degrees are accepted, including negative values.

Eg `display.rotate(44)` will rotate 0 but `display.rotate(46)` will rotate 90 degrees.

Addresses issue #153.

### CODE REVIEW

**Comment by dpgeorge** [comment]
@microbit-carlos does it make sense to accept floating point values as well, in case the user is using a formula to compute the angle?

**Comment by microbit-carlos** [comment]
Thanks Damien!

> @microbit-carlos does it make sense to accept floating point values as well, in case the user is using a formula to compute the angle?

Yes, accepting floats as well would be useful.

**Comment by dpgeorge** [comment]
Updated to accept floats as input rotation angle.

**Review by microbit-carlos — APPROVED** [review]
Tested and looks great, thanks Damien!

**Pull request merged**
